### ISSUE TITLE
Compilation fails with Mqtt-option enabled

### ISSUE THREAD

**Issue by mafe** [maniac103/ems-collector#19] opened 2016-11-12 14:38 UTC
I want to use the ems-collector with MQTT, but it fails while compiling:

`g++ -Wall -c -O2 -std=c++1y -DHAVE_DAEMONIZE -I../../mqtt_client_cpp/include -DMQTT_NO_TLS -DHAVE_MQTT MqttAdapter.cpp
MqttAdapter.cpp: In Konstruktor »MqttAdapter::MqttAdapter(boost::asio::io_service&, EmsCommandSender*, const string&, const string&)«:
MqttAdapter.cpp:32:21: Fehler: keine passende Funktion für Aufruf von »mqtt::client<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::io_service::strand>::client(std::shared_ptr<mqtt::client<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::io_service::strand> >)«
     m_retryTimer(ios)
                     ^
In file included from ../../mqtt_client_cpp/include/mqtt_client_cpp.hpp:8:0,
                 from MqttAdapter.h:28,
                 from MqttAdapter.cpp:22:
../../mqtt_client_cpp/include/mqtt/client.hpp:301:5: Anmerkung: candidate: mqtt::client<Socket, Strand>::client(boost::asio::io_service&, std::__cxx11::string, std::__cxx11::string, bool) [with Socket = boost::asio::basic_stream_socket<boost::asio::ip::tcp>; Strand = boost::asio::io_service::strand; std::__cxx11::string = std::__cxx11::basic_string<char>]
     client(as::io_service& ios,
     ^~~~~~
../../mqtt_client_cpp/include/mqtt/client.hpp:301:5: Anmerkung:   Kandidat erwartet 4 Argumente, 1 angegeben
make: *** [Makefile:49: MqttAdapter.o] Fehler 1
`

Do you see, what causes the error?

- libboost v1.62

**Comment by maniac103** [comment] 2017-02-18 20:37
This was caused by MQTT library changes, should be fixed now.

**Closed by maniac103** 2017-02-18 20:37 UTC
